backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "info"
    label: "Info"
    folder: "content"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Page Type", name: "pagetype", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }